version: '3'

services:
  map:
    image: 
      name: my-french-openstreetmap-tile-server
      context: .
      file: Dockerfile
    volumes:
      - osm-data:/data/database/
    ports:
      - "8080:80"
    command: "run"

volumes:
  osm-data:
    external: true
